#pragma once
// GHOST RECOVER — per-format registration aggregator (generated).
#include "ghost/carve.h"
#include "../sig_common.h"

namespace ghost {
void registerFmt_zip(Registry& r);
void registerFmt_gzip(Registry& r);
void registerFmt_bzip2(Registry& r);
void registerFmt_xz(Registry& r);
void registerFmt_sevenzip(Registry& r);
void registerFmt_rar(Registry& r);
void registerFmt_tar(Registry& r);
void registerFmt_ar(Registry& r);
void registerFmt_cab(Registry& r);
void registerFmt_zstd(Registry& r);
void registerFmt_lz4(Registry& r);
void registerFmt_lzip(Registry& r);
void registerFmt_lzma(Registry& r);
void registerFmt_rpm(Registry& r);
void registerFmt_cpio(Registry& r);
void registerFmt_lzh(Registry& r);
void registerFmt_ace(Registry& r);
void registerFmt_sit(Registry& r);
void registerFmt_wim(Registry& r);
void registerFmt_dmg(Registry& r);
void registerFmt_iso(Registry& r);
void registerFmt_squashfs(Registry& r);
void registerFmt_cramfs(Registry& r);
void registerFmt_mp4(Registry& r);
void registerFmt_wav(Registry& r);
void registerFmt_asf(Registry& r);
void registerFmt_mp3(Registry& r);
void registerFmt_flac(Registry& r);
void registerFmt_ogg(Registry& r);
void registerFmt_aac(Registry& r);
void registerFmt_ac3(Registry& r);
void registerFmt_iff(Registry& r);
void registerFmt_amr(Registry& r);
void registerFmt_midi(Registry& r);
void registerFmt_dts(Registry& r);
void registerFmt_ape(Registry& r);
void registerFmt_wv(Registry& r);
void registerFmt_mpc(Registry& r);
void registerFmt_au(Registry& r);
void registerFmt_caf(Registry& r);
void registerFmt_voc(Registry& r);
void registerFmt_mod(Registry& r);
void registerFmt_json(Registry& r);
void registerFmt_shebang(Registry& r);
void registerFmt_python(Registry& r);
void registerFmt_c(Registry& r);
void registerFmt_go(Registry& r);
void registerFmt_java(Registry& r);
void registerFmt_php(Registry& r);
void registerFmt_rust(Registry& r);
void registerFmt_sql(Registry& r);
void registerFmt_dockerfile(Registry& r);
void registerFmt_yaml(Registry& r);
void registerFmt_toml(Registry& r);
void registerFmt_ini(Registry& r);
void registerFmt_cmake(Registry& r);
void registerFmt_csv(Registry& r);
void registerFmt_vcard(Registry& r);
void registerFmt_ical(Registry& r);
void registerFmt_gpx(Registry& r);
void registerFmt_kml(Registry& r);
void registerFmt_pem(Registry& r);
void registerFmt_ssh(Registry& r);
void registerFmt_der(Registry& r);
void registerFmt_jks(Registry& r);
void registerFmt_kdbx(Registry& r);
void registerFmt_kdb(Registry& r);
void registerFmt_gpg(Registry& r);
void registerFmt_bitcoin(Registry& r);
void registerFmt_sqlite(Registry& r);
void registerFmt_sqlite_wal(Registry& r);
void registerFmt_mdb(Registry& r);
void registerFmt_bdb(Registry& r);
void registerFmt_leveldb(Registry& r);
void registerFmt_firebird(Registry& r);
void registerFmt_mssql(Registry& r);
void registerFmt_parquet(Registry& r);
void registerFmt_orc(Registry& r);
void registerFmt_avro(Registry& r);
void registerFmt_hdf5(Registry& r);
void registerFmt_netcdf(Registry& r);
void registerFmt_feather(Registry& r);
void registerFmt_npy(Registry& r);
void registerFmt_mat(Registry& r);
void registerFmt_pickle(Registry& r);
void registerFmt_pdf(Registry& r);
void registerFmt_ps(Registry& r);
void registerFmt_ooxml(Registry& r);
void registerFmt_xls(Registry& r);
void registerFmt_ppt(Registry& r);
void registerFmt_doc(Registry& r);
void registerFmt_rtf(Registry& r);
void registerFmt_mobi(Registry& r);
void registerFmt_djvu(Registry& r);
void registerFmt_chm(Registry& r);
void registerFmt_one(Registry& r);
void registerFmt_wpd(Registry& r);
void registerFmt_html(Registry& r);
void registerFmt_xml(Registry& r);
void registerFmt_latex(Registry& r);
void registerFmt_msg(Registry& r);
void registerFmt_pst(Registry& r);
void registerFmt_mbox(Registry& r);
void registerFmt_eml(Registry& r);
void registerFmt_dbx(Registry& r);
void registerFmt_elf(Registry& r);
void registerFmt_pe(Registry& r);
void registerFmt_macho(Registry& r);
void registerFmt_class(Registry& r);
void registerFmt_dex(Registry& r);
void registerFmt_wasm(Registry& r);
void registerFmt_pyc(Registry& r);
void registerFmt_sfnt(Registry& r);
void registerFmt_ttc(Registry& r);
void registerFmt_woff(Registry& r);
void registerFmt_pcap(Registry& r);
void registerFmt_pcapng(Registry& r);
void registerFmt_evtx(Registry& r);
void registerFmt_evt(Registry& r);
void registerFmt_regf(Registry& r);
void registerFmt_lnk(Registry& r);
void registerFmt_prefetch(Registry& r);
void registerFmt_job(Registry& r);
void registerFmt_jpeg(Registry& r);
void registerFmt_png(Registry& r);
void registerFmt_gif(Registry& r);
void registerFmt_bmp(Registry& r);
void registerFmt_tiff(Registry& r);
void registerFmt_raf(Registry& r);
void registerFmt_x3f(Registry& r);
void registerFmt_bigtiff(Registry& r);
void registerFmt_webp(Registry& r);
void registerFmt_ico(Registry& r);
void registerFmt_psd(Registry& r);
void registerFmt_xcf(Registry& r);
void registerFmt_jp2(Registry& r);
void registerFmt_j2k(Registry& r);
void registerFmt_jxl(Registry& r);
void registerFmt_qoi(Registry& r);
void registerFmt_dds(Registry& r);
void registerFmt_exr(Registry& r);
void registerFmt_hdr(Registry& r);
void registerFmt_pcx(Registry& r);
void registerFmt_icns(Registry& r);
void registerFmt_emf(Registry& r);
void registerFmt_wmf(Registry& r);
void registerFmt_svg(Registry& r);
void registerFmt_cdr(Registry& r);
void registerFmt_dwg(Registry& r);
void registerFmt_dxf(Registry& r);
void registerFmt_stl(Registry& r);
void registerFmt_blend(Registry& r);
void registerFmt_fbx(Registry& r);
void registerFmt_glb(Registry& r);
void registerFmt_torrent(Registry& r);
void registerFmt_plist(Registry& r);
void registerFmt_openvpn(Registry& r);
void registerFmt_mkv(Registry& r);
void registerFmt_avi(Registry& r);
void registerFmt_flv(Registry& r);
void registerFmt_mpegts(Registry& r);
void registerFmt_mpegps(Registry& r);
void registerFmt_mpegves(Registry& r);
void registerFmt_rm(Registry& r);
void registerFmt_mxf(Registry& r);
void registerFmt_ivf(Registry& r);
void registerFmt_y4m(Registry& r);
void registerFmt_bik(Registry& r);
void registerFmt_swf(Registry& r);
void registerFmt_qcow(Registry& r);
void registerFmt_vmdk(Registry& r);
void registerFmt_vdi(Registry& r);
void registerFmt_vhd(Registry& r);
void registerFmt_vhdx(Registry& r);
void registerFmt_ova(Registry& r);
void registerFmt_aff(Registry& r);
void registerFmt_alz(Registry& r);
void registerFmt_android_boot(Registry& r);
void registerFmt_arc(Registry& r);
void registerFmt_arj(Registry& r);
void registerFmt_bpg(Registry& r);
void registerFmt_crw(Registry& r);
void registerFmt_dbf(Registry& r);
void registerFmt_dmp(Registry& r);
void registerFmt_dvi(Registry& r);
void registerFmt_esedb(Registry& r);
void registerFmt_ewf(Registry& r);
void registerFmt_fdf(Registry& r);
void registerFmt_flif(Registry& r);
void registerFmt_kgb(Registry& r);
void registerFmt_mrw(Registry& r);
void registerFmt_nes(Registry& r);
void registerFmt_nsv(Registry& r);
void registerFmt_ofr(Registry& r);
void registerFmt_pak(Registry& r);
void registerFmt_pcf(Registry& r);
void registerFmt_pict(Registry& r);
void registerFmt_ply(Registry& r);
void registerFmt_pnm(Registry& r);
void registerFmt_qed(Registry& r);
void registerFmt_qxp(Registry& r);
void registerFmt_ra(Registry& r);
void registerFmt_reg(Registry& r);
void registerFmt_rzip(Registry& r);
void registerFmt_sgi(Registry& r);
void registerFmt_sqx(Registry& r);
void registerFmt_tta(Registry& r);
void registerFmt_uharc(Registry& r);
void registerFmt_vqf(Registry& r);
void registerFmt_wad(Registry& r);
void registerFmt_wtv(Registry& r);
void registerFmt_xar(Registry& r);
void registerFmt_xpm(Registry& r);
void registerFmt_zoo(Registry& r);
void registerFmt_zpaq(Registry& r);

inline void registerAllFormats(Registry& r) {
    registerFmt_zip(r);
    registerFmt_gzip(r);
    registerFmt_bzip2(r);
    registerFmt_xz(r);
    registerFmt_sevenzip(r);
    registerFmt_rar(r);
    registerFmt_tar(r);
    registerFmt_ar(r);
    registerFmt_cab(r);
    registerFmt_zstd(r);
    registerFmt_lz4(r);
    registerFmt_lzip(r);
    registerFmt_lzma(r);
    registerFmt_rpm(r);
    registerFmt_cpio(r);
    registerFmt_lzh(r);
    registerFmt_ace(r);
    registerFmt_sit(r);
    registerFmt_wim(r);
    registerFmt_dmg(r);
    registerFmt_iso(r);
    registerFmt_squashfs(r);
    registerFmt_cramfs(r);
    registerFmt_mp4(r);
    registerFmt_wav(r);
    registerFmt_asf(r);
    registerFmt_mp3(r);
    registerFmt_flac(r);
    registerFmt_ogg(r);
    registerFmt_aac(r);
    registerFmt_ac3(r);
    registerFmt_iff(r);
    registerFmt_amr(r);
    registerFmt_midi(r);
    registerFmt_dts(r);
    registerFmt_ape(r);
    registerFmt_wv(r);
    registerFmt_mpc(r);
    registerFmt_au(r);
    registerFmt_caf(r);
    registerFmt_voc(r);
    registerFmt_mod(r);
    registerFmt_json(r);
    registerFmt_shebang(r);
    registerFmt_python(r);
    registerFmt_c(r);
    registerFmt_go(r);
    registerFmt_java(r);
    registerFmt_php(r);
    registerFmt_rust(r);
    registerFmt_sql(r);
    registerFmt_dockerfile(r);
    registerFmt_yaml(r);
    registerFmt_toml(r);
    registerFmt_ini(r);
    registerFmt_cmake(r);
    registerFmt_csv(r);
    registerFmt_vcard(r);
    registerFmt_ical(r);
    registerFmt_gpx(r);
    registerFmt_kml(r);
    registerFmt_pem(r);
    registerFmt_ssh(r);
    registerFmt_der(r);
    registerFmt_jks(r);
    registerFmt_kdbx(r);
    registerFmt_kdb(r);
    registerFmt_gpg(r);
    registerFmt_bitcoin(r);
    registerFmt_sqlite(r);
    registerFmt_sqlite_wal(r);
    registerFmt_mdb(r);
    registerFmt_bdb(r);
    registerFmt_leveldb(r);
    registerFmt_firebird(r);
    registerFmt_mssql(r);
    registerFmt_parquet(r);
    registerFmt_orc(r);
    registerFmt_avro(r);
    registerFmt_hdf5(r);
    registerFmt_netcdf(r);
    registerFmt_feather(r);
    registerFmt_npy(r);
    registerFmt_mat(r);
    registerFmt_pickle(r);
    registerFmt_pdf(r);
    registerFmt_ps(r);
    registerFmt_ooxml(r);
    registerFmt_xls(r);
    registerFmt_ppt(r);
    registerFmt_doc(r);
    registerFmt_rtf(r);
    registerFmt_mobi(r);
    registerFmt_djvu(r);
    registerFmt_chm(r);
    registerFmt_one(r);
    registerFmt_wpd(r);
    registerFmt_html(r);
    registerFmt_xml(r);
    registerFmt_latex(r);
    registerFmt_msg(r);
    registerFmt_pst(r);
    registerFmt_mbox(r);
    registerFmt_eml(r);
    registerFmt_dbx(r);
    registerFmt_elf(r);
    registerFmt_pe(r);
    registerFmt_macho(r);
    registerFmt_class(r);
    registerFmt_dex(r);
    registerFmt_wasm(r);
    registerFmt_pyc(r);
    registerFmt_sfnt(r);
    registerFmt_ttc(r);
    registerFmt_woff(r);
    registerFmt_pcap(r);
    registerFmt_pcapng(r);
    registerFmt_evtx(r);
    registerFmt_evt(r);
    registerFmt_regf(r);
    registerFmt_lnk(r);
    registerFmt_prefetch(r);
    registerFmt_job(r);
    registerFmt_jpeg(r);
    registerFmt_png(r);
    registerFmt_gif(r);
    registerFmt_bmp(r);
    registerFmt_tiff(r);
    registerFmt_raf(r);
    registerFmt_x3f(r);
    registerFmt_bigtiff(r);
    registerFmt_webp(r);
    registerFmt_ico(r);
    registerFmt_psd(r);
    registerFmt_xcf(r);
    registerFmt_jp2(r);
    registerFmt_j2k(r);
    registerFmt_jxl(r);
    registerFmt_qoi(r);
    registerFmt_dds(r);
    registerFmt_exr(r);
    registerFmt_hdr(r);
    registerFmt_pcx(r);
    registerFmt_icns(r);
    registerFmt_emf(r);
    registerFmt_wmf(r);
    registerFmt_svg(r);
    registerFmt_cdr(r);
    registerFmt_dwg(r);
    registerFmt_dxf(r);
    registerFmt_stl(r);
    registerFmt_blend(r);
    registerFmt_fbx(r);
    registerFmt_glb(r);
    registerFmt_torrent(r);
    registerFmt_plist(r);
    registerFmt_openvpn(r);
    registerFmt_mkv(r);
    registerFmt_avi(r);
    registerFmt_flv(r);
    registerFmt_mpegts(r);
    registerFmt_mpegps(r);
    registerFmt_mpegves(r);
    registerFmt_rm(r);
    registerFmt_mxf(r);
    registerFmt_ivf(r);
    registerFmt_y4m(r);
    registerFmt_bik(r);
    registerFmt_swf(r);
    registerFmt_qcow(r);
    registerFmt_vmdk(r);
    registerFmt_vdi(r);
    registerFmt_vhd(r);
    registerFmt_vhdx(r);
    registerFmt_ova(r);
    registerFmt_aff(r);
    registerFmt_alz(r);
    registerFmt_android_boot(r);
    registerFmt_arc(r);
    registerFmt_arj(r);
    registerFmt_bpg(r);
    registerFmt_crw(r);
    registerFmt_dbf(r);
    registerFmt_dmp(r);
    registerFmt_dvi(r);
    registerFmt_esedb(r);
    registerFmt_ewf(r);
    registerFmt_fdf(r);
    registerFmt_flif(r);
    registerFmt_kgb(r);
    registerFmt_mrw(r);
    registerFmt_nes(r);
    registerFmt_nsv(r);
    registerFmt_ofr(r);
    registerFmt_pak(r);
    registerFmt_pcf(r);
    registerFmt_pict(r);
    registerFmt_ply(r);
    registerFmt_pnm(r);
    registerFmt_qed(r);
    registerFmt_qxp(r);
    registerFmt_ra(r);
    registerFmt_reg(r);
    registerFmt_rzip(r);
    registerFmt_sgi(r);
    registerFmt_sqx(r);
    registerFmt_tta(r);
    registerFmt_uharc(r);
    registerFmt_vqf(r);
    registerFmt_wad(r);
    registerFmt_wtv(r);
    registerFmt_xar(r);
    registerFmt_xpm(r);
    registerFmt_zoo(r);
    registerFmt_zpaq(r);
}

}  // namespace ghost
